name: Worker

on:
  workflow_dispatch:
    inputs:
      packages00URL:
        description: "the download link for Packages-00.tar.gz"
        required: false
      target:
        description: "OpenWRT Target System(Value: x86, bcm27xx, ...)"
        required: false
        default: "x86"
      subtarget:
        description: "OpenWRT Subtarget(Value: 64, bcm2711, ...)"
        required: false
        default: "64"
      subsequent:
        description: "trigger subsequent workflow after build success(Value: 0, 1)"
        required: false
        default: "0"
jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        worker:
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06"
          - "07"
          - "08"
          - "09"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
    steps:
      - name: Free disk space
        run: |
          sudo -E swapoff -a
          sudo -E rm -f /swapfile
          sudo -E docker image prune -a -f
          sudo -E snap set system refresh.retain=2
          sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu* powershell* msodbc*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
          [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Checkout OpenWRT repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: pull docker image
        run: |
          docker pull elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}
          docker tag elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }} elonh/opde:worker
      - name: Copy SDK
        run: |
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker sudo chown opde:opde -R /openwrt_bak
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker rsync -av /openwrt/ /openwrt_bak
      - name: Opde feeds
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde feeds
      - name: Opde config
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde config -i /worker/${{matrix.worker}}.worker.conf
      - name: Show config
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker cat .opde/min-config.in
      - name: Opde download
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde download
      - name: Opde build
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde build
      - name: Fix premission
        run: sudo chown $(id -u -n):$(id -g -n) -R openwrt

      - name: Prepare upload
        run: |
          mkdir /tmp/opdelogs && cp -rf ./openwrt/.opde ./openwrt/logs /tmp/opdelogs
          mv ./openwrt/bin /tmp/opdebin
          rm openwrt -rf
      - uses: actions/upload-artifact@v2
        with:
          name: Packages-${{matrix.worker}}
          path: /tmp/opdebin
      - uses: actions/upload-artifact@v2
        with:
          name: Log-${{matrix.worker}}
          path: /tmp/opdelogs
      # -
      # name: debug # docker run -it -v $PWD:/openwrt elonh/opde:base bash
      # uses: mxschmitt/action-tmate@v2
      # if: always()

  bundle_packages:
    needs:
      - worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare dowload artifacts
        run: |
          mkdir openwrt/bin -p
      - uses: actions/download-artifact@v2
        with:
          name: Packages-20
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-19
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-18
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-17
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-16
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-15
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-14
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-13
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-12
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-11
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-10
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-09
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-08
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-07
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-06
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-05
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-04
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-03
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-02
          path: openwrt/bin
      - uses: actions/download-artifact@v2
        with:
          name: Packages-01
          path: openwrt/bin
      - name: Pull docker image
        run: -|
          docker pull elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}
          docker tag elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }} elonh/opde:worker
      - name: Download Packages-00
        if: ${{ github.event.inputs.packages00URL }}
        run: |-
          docker run -v $PWD:/openwrt elonh/opde:worker sudo transfer ${{github.event.inputs.packages00URL}} -o Packages-00.tar.gz
          sudo chown $(id -u -n):$(id -g -n) Packages-00.tar.gz
          sha256sum Packages-00.tar.gz
          cd openwrt/bin
          tar -xzf ../../Packages-00.tar.gz
      - name: Count ipk
        run: |-
          find openwrt/bin -name "*.ipk" | grep -c ""
          find openwrt/bin -name "*.ipk"
      - name: Import key
        env:
          BUILD_KEY: ${{secrets.BUILD_KEY_PRIVATE}}
          BUILD_KEY_PUBLIC: ${{secrets.BUILD_KEY_PUBLIC}}
        run: |
          echo $BUILD_KEY > openwrt/build-key
          echo $BUILD_KEY_PUBLIC > openwrt/build-key.pub
      - name: Copy SDK
        run: |
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker sudo chown opde:opde -R /openwrt_bak
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker rsync -a /openwrt/ /openwrt_bak
      - name: Opde feeds
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde feeds
      - name: Opde config
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde config
      - name: Opde download
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde download
      - name: Opde build
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde reindex
      - name: Fix premission
        run: sudo chown $(id -u -n):$(id -g -n) -R openwrt
      - uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: openwrt/bin

  bundle_logs:
    needs:
      - worker
    runs-on: ubuntu-latest
    steps:
      - name: Prepare dowload artifacts
        run: |
          mkdir openwrt -p
      - uses: actions/download-artifact@v2
        with:
          name: Log-20
          path: openwrt/Log-20
      - uses: actions/download-artifact@v2
        with:
          name: Log-19
          path: openwrt/Log-19
      - uses: actions/download-artifact@v2
        with:
          name: Log-18
          path: openwrt/Log-18
      - uses: actions/download-artifact@v2
        with:
          name: Log-17
          path: openwrt/Log-17
      - uses: actions/download-artifact@v2
        with:
          name: Log-16
          path: openwrt/Log-16
      - uses: actions/download-artifact@v2
        with:
          name: Log-15
          path: openwrt/Log-15
      - uses: actions/download-artifact@v2
        with:
          name: Log-14
          path: openwrt/Log-14
      - uses: actions/download-artifact@v2
        with:
          name: Log-13
          path: openwrt/Log-13
      - uses: actions/download-artifact@v2
        with:
          name: Log-12
          path: openwrt/Log-12
      - uses: actions/download-artifact@v2
        with:
          name: Log-11
          path: openwrt/Log-11
      - uses: actions/download-artifact@v2
        with:
          name: Log-10
          path: openwrt/Log-10
      - uses: actions/download-artifact@v2
        with:
          name: Log-09
          path: openwrt/Log-09
      - uses: actions/download-artifact@v2
        with:
          name: Log-08
          path: openwrt/Log-08
      - uses: actions/download-artifact@v2
        with:
          name: Log-07
          path: openwrt/Log-07
      - uses: actions/download-artifact@v2
        with:
          name: Log-06
          path: openwrt/Log-06
      - uses: actions/download-artifact@v2
        with:
          name: Log-05
          path: openwrt/Log-05
      - uses: actions/download-artifact@v2
        with:
          name: Log-04
          path: openwrt/Log-04
      - uses: actions/download-artifact@v2
        with:
          name: Log-03
          path: openwrt/Log-03
      - uses: actions/download-artifact@v2
        with:
          name: Log-02
          path: openwrt/Log-02
      - uses: actions/download-artifact@v2
        with:
          name: Log-01
          path: openwrt/Log-01
      - name: Compress Logs
        run: tar -czvf Logs.tar.gz openwrt
      - name: Pull docker image
        run: -|
          docker pull elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}
          docker tag elonh/opde:worker-${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }} elonh/opde:worker
      - name: Upload Logs to artifact
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: Logs.tar.gz
      - name: Upload Logs to web
        run: |
          sha256sum Logs.tar.gz
          docker run -v $PWD/Logs.tar.gz:/openwrt/Logs.tar.gz elonh/opde:worker sudo chown opde:opde Logs.tar.gz
          docker run -v $PWD/Logs.tar.gz:/openwrt/Logs.tar.gz elonh/opde:worker transfer trs Logs.tar.gz > downloadLink
      - name: Extract link
        id: logs-web
        run: |
          link=$(cat downloadLink | grep 'Download Link:' | grep -o 'https://.*')
          echo $link
          echo "::set-output name=LINK::$link"
      - name: Invoke Collector workflow
        if: ${{ github.event.inputs.subsequent == '1'}}
        uses: benc-uk/workflow-dispatch@master
        with:
          workflow: Collector
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "dataURL": "${{steps.logs-web.outputs.LINK}}"}'
